on: [push]

name: Linux_Container_Python_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: devconfregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t devconfregistry.azurecr.io/xyz-ym-simple-discord-bot:${{ github.sha }}
        docker push devconfregistry.azurecr.io/xyz-ym-simple-discord-bot:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'xyz-ym-simple-discord-bot'
        images: 'devconfregistry.azurecr.io/xyz-ym-simple-discord-bot:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
